import React,{ createContext } from "react";
import Head from "next/head";
import { Header } from "../components/Header";
import { Nav } from "../components/Nav";
import { Results } from "../components/Results";
import requests from "../utils/request";

export const FavContext = createContext(null);

export default function Home({ results }) {
  // let fav = (favourite) => {
  //   return favourite;
  // };
  let star =4
  return (
    <div>
      <Head>
        <title>Starr</title>
        <link rel="icon" href="/icon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Header favourite={star} />
        <Nav />
        <FavContext.Provider value={star} >
          <Results results={results} />
        </FavContext.Provider>
      </main>
    </div>
  );
}
export async function getServerSideProps(context) {
  let genre = context.query.genre;
  console.log(genre, "genre");
  //const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.Trending.url}`)
  const request = await fetch(`https://api.themoviedb.org/3/trending/all/week?api_key=d90250cf6160951db8f4f8c9b0d644a3`)
  .then((response) => response.json())
  .catch((err) => console.log(err));
  return {
    props: {
      results: request.results || null,
    },
  };
}
